language: elixir
elixir:
  - 1.7.2
  - 1.8.2
  - 1.9.2
otp_release:
  - 21.3
  - 22.1
script:
  - mix deps.compile
  - mix compile --warnings-as-errors
  - mix test
  - mix credo --strict
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - mat@geeky.net
